// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://zhimiao.org",
        "contact": {
            "name": "API Support",
            "url": "http://tools.zhimiao.org",
            "email": "mail@xiaoliu.org"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/hello": {
            "get": {
                "tags": [
                    "default"
                ],
                "summary": "测试页面",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/member/login": {
            "post": {
                "tags": [
                    "账户"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "default",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/vo.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.LoginResp"
                        }
                    }
                }
            }
        },
        "/v1/member/userinfo": {
            "put": {
                "security": [
                    {
                        "ApiAuth": []
                    }
                ],
                "description": "更新用户信息",
                "tags": [
                    "账户"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "default",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/vo.UserInfoUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "vo.LoginReq": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "js_code": {
                    "type": "string"
                }
            }
        },
        "vo.LoginResp": {
            "type": "object",
            "properties": {
                "open_id": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "vo.UserInfoUpdateReq": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "description": "头像",
                    "type": "string"
                },
                "city": {
                    "description": "市",
                    "type": "string"
                },
                "country": {
                    "description": "国家",
                    "type": "string"
                },
                "gender": {
                    "description": "1-男性 2-女性",
                    "type": "integer"
                },
                "nickname": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "province": {
                    "description": "省",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api",
	Schemes:     []string{"http", "https"},
	Title:       "纸喵 API",
	Description: "纸喵软件系列",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
